### PR TITLE
Added more projects using JAX (GP, cosmo, sym).

### PR DESCRIPTION
**Pull request by jejjohnson**
* GPJax - a model/project for now but it could potentially be a fully-fledged package in the future.
* kalman-jax - a model/project of a suite of methods.
* symjax - a full-fledged package for symbolic programming
* jax-cosmo - a full-fledged package for cosmology
* mcx - a full-fledged package for bayesian inference.
* jaxns - a model for nested sampling (mcmc variant)
* efax - models datasets using the exponential family.

### CODE REVIEW

**Comment by n2cholas** [comment]
These are really great, thanks so much! It makes me wonder whether it's worth creating a "Young Libraries" section. Some of these libraries are very useful and well-made, but haven't been battle-tested yet by a user-base, making them hard to classify as "awesome". Any thoughts on that?

**Comment by jejjohnson** [comment]
I definitely agree with you. The number of stars is a good indicator but I think it's worth creating a section or even just a tag. Highlighting new libraries with a dedicated may help exposure as well!

**Comment by n2cholas** [comment]
Great, feel free to create a "New Libraries" or "Young Libraries" section and move the appropriate projects there!

**Comment by n2cholas** [comment]
Thanks @jejjohnson for creating that section!

**Pull request merged**
