### PR TITLE
Added XLB library

### PR DESCRIPTION
**Pull request by mehdiataei**
Added XLB library
https://github.com/Autodesk/XLB

### CODE REVIEW

**Comment by n2cholas** [comment]
Thanks for the PR! Could you ensure this library lives in only one section?

**Comment by mehdiataei** [comment]
Hey @n2cholas. The library is only in one section. The second entry links to the whitepaper of the library in the section for "AX-based library whitepapers". 

I updated the paper title to the newest. 

Thanks.

**Comment by n2cholas** [comment]
Thanks, I will have to resolve the linter issue before I can merge this in. Will take a look in a few days. If you're able to resolve it earlier please feel free to do so.

**Comment by mehdiataei** [comment]
Thanks. Fixed the linter issue there was no need for the two links.

**Pull request merged**
